create table todos (                                                        
    id bigint generated by default as identity primary key,                   
    user_id uuid references auth.users not null,                              
    text text not null,
    image_url text,
    is_completed boolean default false,                                       
    is_important boolean default false,                                       
    created_at timestamp with time zone default timezone('utc'::text, now())  
  not null                                                                    
  );  

alter table todos enable row level security; 

create policy "Individuals can view their own todos." on todos for          
select using (auth.uid() = user_id);   

create policy "Individuals can create todos." on todos for                  
      insert with check (auth.uid() = user_id); 

create policy "Individuals can update their own todos." on todos for        
      update using (auth.uid() = user_id); 

create policy "Individuals can delete their own todos." on todos for
      delete using (auth.uid() = user_id);

-- Enable Realtime for todos table
alter publication supabase_realtime add table todos; 
ALTER TABLE todos REPLICA IDENTITY FULL;